### PR TITLE
Add support for 1.19

### PR DESCRIPTION
**Pull request by jmattingley23**
Adds support for 1.19 / 1.19.2

I don't really expect this to get merged as its bringing in a lot of other commits under it that will make code review a pain but I was able to get this working so I figured I'd at least put it out there for other people to use and to serve as reference for any future development work.

The biggest relevant change in 1.19 seems to be that the concept of biome categories no longer exists.  As a short term fix I just used the biome name to map from the old minecraft categories to DynamicSurroundings biome traits, but going forward it would probably be best to move this into some sort of static mapping or migrate away from the concept of biome categories entirely.

### CODE REVIEW

**Comment by coornio** [comment]
Hey there. I wanted to point out that something is pretty darn wrong in 1.19. The engine itself works fine, but none of the biome loops are being played. Can confirm that the 1.18.2 version does. Quick debug screen:

image

I reckon it has something to do with the biome changes in 1.19. I would be grateful if someone who's definitely more knowledgeable than me could attempt to fix this. I like this mod's sounds much more than AmbientSounds :)

**Comment by cpm9** [comment]
Can we get a link to a build/action for download? Thanks @jmattingley23 @coornio

**Comment by coornio** [comment]
> Can we get a link to a build/action for download? Thanks @jmattingley23 @coornio

Go to **Commits**, scroll all the way to the bottom to the last one, click the **< >** button on it, then opt to download the project source as a zip. Extract the folder somewhere, then open a CMD window at that location and type `gradlew build`, then wait it out and you'll find the .jar you want in a folder named "binaries" (I might be remembering that wrong).

**Comment by jmattingley23** [comment]
Yup that's pretty much the process, here's the one that I built when I made the PR (hopefully its ok to post it like this):  [DynamicSurroundings-Fabric-1.19-0.0.4.zip](https://github.com/OreCruncher/DynamicSurroundingsFabric/files/8953011/DynamicSurroundings-Fabric-1.19-0.0.4.zip)

**Comment by jmattingley23** [comment]
> Thanks but isn't there a way to make the .jar compiled in github with a build action artifiact something like this older one for 1.18?

Good point, here's the one from my fork: https://github.com/jmattingley23/DynamicSurroundingsFabric/actions/runs/2478026253

**Comment by coornio** [comment]
> Hmm, I'm not totally sure either. This is my first time contributing to the development of this mod so I'm no expert but I assume you're probably right that it has something to do with the biome category changes. I've been playing with the 1.19 version for a little over a week now and haven't personally noticed any issues with incorrect loops playing or missing loops. In the debug screen are you able to see if the biome traits are getting populated correctly? Or if incorrect ones are being added when you notice the wrong sounds playing? 

It's quite late right now but I can give it another go tomorrow so that I can provide additional info/context. 

Some of my experiences include, but are not exclusive to, the minecart/base sound being omnipresent but inaudible (was this always there?? can't be configured either), guardian laser attack sounds in a frozen ocean/spikes biome with no ocean monument in sight (checked with /locate), lack of ambient loops in forests, meadows, and badlands, rain loop over a river with no rain, and sometimes even occasional mob sounds where they weren't present (I have a minimap so I can see them if they're in range). Odd stuff.

**Comment by Stonehawk** [comment]
Goodness Me, this shows how much of a hopeless n00b I may forever be when it comes to GitHub; I only peeked in the pull requests out of desperation, but it seems you've done exactly what I was hoping someone might have! At least I've learned **one** new thing today...

Thank you for giving this project a gasp of life; it seems to have needed one badly.

Minecraft just hasn't been the same without Dynamic Surroundings.

**Comment by kirmerk1** [comment]
> > Hmm, I'm not totally sure either. This is my first time contributing to the development of this mod so I'm no expert but I assume you're probably right that it has something to do with the biome category changes. I've been playing with the 1.19 version for a little over a week now and haven't personally noticed any issues with incorrect loops playing or missing loops. In the debug screen are you able to see if the biome traits are getting populated correctly? Or if incorrect ones are being added when you notice the wrong sounds playing? 
> 
> It's quite late right now but I can give it another go tomorrow so that I can provide additional info/context.
> 
> Some of my experiences include, but are not exclusive to, the minecart/base sound being omnipresent but inaudible (was this always there?? can't be configured either), guardian laser attack sounds in a frozen ocean/spikes biome with no ocean monument in sight (checked with /locate), lack of ambient loops in forests, meadows, and badlands, rain loop over a river with no rain, and sometimes even occasional mob sounds where they weren't present (I have a minimap so I can see them if they're in range). Odd stuff.

I got the same problem. Have you found the fix?

**Comment by Sunconure11** [comment]
Is this compatible with 1.19.2?

**Comment by Sunconure11** [comment]
The cache for these builds is no longer available.

@jmattingley23

**Comment by jmattingley23** [comment]
> Is this compatible with 1.19.2?

I'd would assume so, I haven't played on 1.19.2 yet though.  If it doesn't work let me know and it should be pretty easy to upgrade.

**Comment by jmattingley23** [comment]
> The cache for these builds is no longer available.
> 
> @jmattingley23

Oops, I guess it expires after a while.  Here's a direct link to download the .jar:

[DynamicSurroundings-Fabric-1.19-0.0.4.zip](https://github.com/OreCruncher/DynamicSurroundingsFabric/files/9562419/DynamicSurroundings-Fabric-1.19-0.0.4.zip)

If it expires again you can always build it yourself by cloning the repo and running `gradlew build`

**Comment by jmattingley23** [comment]
### New version (1.19-0.0.5)
Includes a few fixes:

- Fixed a previously existing NPE in the `SoundEventType` class which was preventing biome loops and additional ambient sounds from playing
- Added a bunch of missing biome traits that were lost in the deprecated categories conversion
- Fixed an issue where the debug screen would always show `ERROR?` on the second line

Here's some screenshots showing the working loops & ambient sounds, as well as additional traits & attributes being populated correctly:

Screenshot 2022-09-14 202247

Screenshot 2022-09-14 202151

### Download (tested & working on 1.19.2:
[DynamicSurroundings-Fabric-1.19-0.0.5.zip](https://github.com/OreCruncher/DynamicSurroundingsFabric/files/9571505/DynamicSurroundings-Fabric-1.19-0.0.5.zip)

**Comment by jmattingley23** [comment]
@coornio @kirmerk1 I remember you guys were having issues with the previous version, let me know if this new revision addresses the problems you were seeing

**Comment by coornio** [comment]
> @coornio @kirmerk1 I remember you guys were having issues with the previous version, let me know if this new revision addresses the problems you were seeing

MVP?!

Will give it a shot as soon as I have some time <3

**Comment by Sunconure11** [comment]
Legally speaking, you could probably upload this to CurseForge. I'd suggest looking into this.

**Comment by Archimedes777** [comment]
hi everybody. I don't understand coding mods at all, but I really like this mod. Earlier in this modification there was a sound of selecting tools (sword)(pickaxe and axe had the same sound) (shovel and hoe also had the same sound), there were also sounds of sword attacks and each of the tools. For the first time I heard these sounds from one of the YouTubers, I really liked these sounds, in general, that's why I started looking for this mod, but as it turned out, in the latest versions on fabric made with the help of you and the rest of the community of this mod, there are no these sounds. The last time this feature was encountered on forge versions. One of these versions is 1.16.5 from the developer of this mod. The second one is from 1.19.2 (I understand that this version was also created by the community). I attached screenshots of these versions from the curseforge website. Since I am not fully versed in creating mods, I would like to ask you to add these sounds. I don't understand why these sounds were lost, didn't you really like them?
msedge_im2s29SBYv
msedge_EGvdAopZIi
msedge_9fNgg8cpSw
msedge_ScRCiK8czl

**Comment by Archimedes777** [comment]
I understand everything. it was enough to go to the mod settings.))))

**Comment by rc6ty** [comment]
Hey, I observed a sound clipping issue recently when beeing near large amounts of flowing water, did anyone else encountered a simlar thing? video demonstrating the problem: https://imgur.com/a/I0tTI2i

**Comment by LucidAPs** [comment]
Hey, can we get a 1.19.3 version too? :)

**Comment by Neuxs0** [comment]
yeah, a 1.19.3 version would be nice

**Comment by Neuxs0** [comment]
since 1.19.3 support still isn't out imma start working on it

**Comment by BlueSky-fur** [comment]
I will try to make a working version for 1.19.4 and open a PR afterwards

**Comment by MotMomet** [comment]
can u update it to 1.20 please?

**Pull request merged**
